### ISSUE TITLE
Some files not included

### ISSUE THREAD

**Issue by redorav** [calibre2opds/calibre2opds#10]
I have a Calibre database that also includes pptx, video and zip files. calibre2opds doesn't seem to include these files even if I put the filter to ALL (or even if I include the extension manually). Is there a workaround or a way to add these files?

Thanks

**Comment by calibre2opds** [comment]
If you want additional file types to be recognized by Calibre2opds as ones that can be downloaded then you need to specify them as described at https://wiki.mobileread.com/wiki/Calibre2OpdsCustomize#Mime_Types

**Comment by redorav** [comment]
Thanks a lot! Will do, based on some of the things I read I had the impression issues could be posted here. That wiki page actually answers another question of mine (the xslt to customize the resulting html) so double thanks! In any case I managed to get my pptx included by having a user mime so that's all good.

**Comment by calibre2opds** [comment]
I tend to try and use the forum for questions, and reserve the Issues section here for what are believed to be bugs and/or enhancement requests (i.e. items that are going to need code changes to resolve).   Of course that does not mean that an issue raised in the forum will not result in an issue being raised here as well if it satisfies the criteria i have for putting issues on gitHub.

I might need to look at seeing if I can make the distinction clearer on the calibre2opds.com site.
