### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by worldworm** [calibre2opds/calibre2opds#15]
Your site is not available. 
https://calibre2opds.com

If the URL has changed, please open a pull request at
https://github.com/Kickball/awesome-selfhosted or create an issue. Thank you!

awesome-selfhosted/awesome-selfhosted#1767

**Comment by calibre2opds** [comment]
This is because nobody was prepared to pay the fee Wordpress was demanding to keep the site active for a blogging facility that was virtually never used.  Documentation, source and download sites still work.

**Comment by RogueScholar** [comment]
Just a passing thought, but have you given any thought to taking advantage of [GitHub Pages](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/creating-a-github-pages-site) as a means to publish some basic information about the project, download and bug reporting links, and a donation button? You have the perfect username here for it and it's entirely without cost; just take your pick of the FOSS static site generators (I've gotten comfortable with [Pelican](https://docs.getpelican.com/en/latest/tips.html#publishing-to-github), myself, but [Jekyll](https://jekyllrb.com) and [Hugo](https://gohugo.io) are also quite good...and decidedly less "Python-y") and with the material from the [MobileRead Wiki](https://wiki.mobileread.com/wiki/Calibre2Opds_Index) copied over with a few updated links and I'd be surprised if it wasn't live in under a couple hours. :rocket:

I certainly don't mean to sharpshoot you on this, it just seems a shame for a project with as much stature as this one not to have a foothold on the web somewhere, so I thought I'd throw the idea out there. Plus I detest the fact that the vile person now squatting on the old domain that's still linked on the MR Wiki is getting their capitalist jollies on the back of one of the better open source tools I use. Anyhow, thank you for making something so useful and giving it away. I hope you have a very happy and healthy holiday season. :christmas_tree:

**Comment by ghfbsd** [comment]
As of Aug. 2021, the present occupant of calibre2opds (dot) com appears to deliver malware to those who access the home page.

I'd suggest that the maintainers search for and purge any old links in the code & current online docs.

**Comment by worldworm** [comment]
Closing this topic as it is stale and the project seems abandoned.
